name: Sophia CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build / CI Status
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements file"

      - name: Run basic test
        run: echo "Works"

      
